# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad1a6f225e645c979397580f23a4c19a1b7b3c55247ddf0b7769393bee87e5de567dc547068c4138dd6ab75146502c9354357ec01afbe28b16cdde70a24f16c9

test:
  secret_key_base: 4f4cc5fac8bc6c45a063033e6b53807bd93cd0aff8edd19b20d10cff9bda6ce4d8997232f422f839aa529abf4b16902bef35265d41703786cde29bb5ca43fe86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
