# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b85f5056b913f4657eb49b85057698ed69351ae1d37649f9453e9944b0328acb0437964a043b70046895c751ffe1e6184a5666f1cbbd7c5a1f28ff8c19a9074a

test:
  secret_key_base: ca0fd2f89bfef1d8b43ee5b3c1a36d402f02351e4fba3dca18d1daa1dc7dea2e3bdee8ed86491491e2484f9cdb629b31d147218c0e83a5005ad4b8edf42110ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
